openapi: 3.1.0
info:
  version: 0.0.1
  title: art_api
  description: API to manage the art database
  contact:
    name: Ramiro Storni
paths:
  # ARTWORKS
  '/artworks':
    get:
      responses:
        '200':
          $ref: '#/components/responses/get_artworks_200'
  '/artwork/{artwork_id}':
    get:
      parameters:
      - $ref: '#/components/parameters/path_artwork_id'
      responses:
        '200':
          $ref: '#/components/responses/get_artwork_200'
  # AUCTIONS
  '/auctions':
    get:
      responses:
        '200':
          $ref: '#/components/responses/get_auctions_200'
  '/auction/{auction_id}':
    get:
      parameters:
        - $ref: '#/components/parameters/path_auction_id'
      responses:
        '200':
          $ref: '#/components/responses/get_auction_200'
  # AUCTION ITEMS
  '/auction_items/{auction_id}':
    get:
      parameters:
        - $ref: '#/components/parameters/path_auction_id'
      responses:
        '200':
          $ref: '#/components/responses/get_auction_items_200'
  '/auction_item/{auction_id}/{auction_item_id}':
    get:
      parameters:
        - $ref: '#/components/parameters/path_auction_id'
        - $ref: '#/components/parameters/path_auction_item_id'
      responses:
        '200':
          $ref: '#/components/responses/get_auction_item_200'
  # BIDS
  '/bids':
    get:
      responses:
        '200': 
          $ref: '#/components/responses/get_bids_200'
components:
  schemas:
    # General Schemas
    id:
      type: string
      description: UUID for a resource
      example: 123e4567-e89b-12d3-a456-426614174000
    name:
      type: string
      description: The humman readable name or tile associated with an object.
    details:
      type: string
      description: Additional details associated with an object.
    datetime:
      type: string
      format: date-time
      description: Date and time associated with some event.
    bid_value:
      type: integer
      description: Represents a monetary bid value.
      example: 3000
    bid_status:
      type: string
      enum: 
        - approved
        - declined
    # Art Object Schemas
    artwork:
      type: object
      description: art object properties
      properties:
        artwork_id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
          example: little walter's toys
        details:
          $ref: '#/components/schemas/details'
          example: Pre-WWI still life painting of Aguste Macke's son's toys. 
        artist:
          $ref: '#/components/schemas/name'
          example: Aguste Macke
          default: Unknown
        creation_date:
          $ref: '#/components/schemas/datetime'
          example: 1912-01-01
        medium:
          $ref: '#/components/schemas/details'
          example: oil on canvas
          default: Unknown
        dimentions:
          $ref: '#/components/schemas/details'
          default: Unknown
      required:
        - artwork_id
        - name
    artwork_list:
      type: array
      description: A list of Artworks
      items:
        $ref: '#/components/schemas/artwork'
    # Auction Schemas
    auction:
      type: object
      description: auction properties
      properties:
        auction_id:
          $ref: '#/components/schemas/id'
        title:
          $ref: '#/components/schemas/name'
          example: Pre-WWI Art - Storni Collection
        details:
          $ref: '#/components/schemas/details'
          example: The best Pre-WWI paintings and sculptures from the Storni collecton.
        start_datetime:
          $ref: '#/components/schemas/datetime'
          example: 2024-12-16T12:45:00Z
        end_datetime:
          $ref: '#/components/schemas/datetime'
          example: 2024-12-25T12:45:00Z
      required:
        - auction_id
        - start_datetime
        - end_datetime
    auction_list:
      type: array
      description: A list of auctions.
      items:
        $ref: '#/components/schemas/auction'
    # Auction Item
    auction_item:
      type: object
      description: Artworks in an auction
      properties:
        auction_item_id:
          $ref: '#/components/schemas/id'
        auction_id:
          $ref: '#/components/schemas/id'
        artwork_id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
        details:
          $ref: '#/components/schemas/details'
        starting_bid:
          $ref: '#/components/schemas/bid_value'
    auction_item_list:
      type: array
      description: A list of auction items.
      items:
        $ref: '#/components/schemas/auction_item'
    # Bids
    bid:
      type: object
      description: Object describing a bid
      properties:
        bid_id:
          $ref: '#/components/schemas/id'
        user_id:
          $ref: '#/components/schemas/id'
        acution_item_id:
          $ref: '#/components/schemas/id'
        bid_timestamp:
          $ref: '#/components/schemas/datetime'
        status:
          $ref: '#/components/schemas/bid_status'
        bid_amount:
          $ref: '#/components/schemas/bid_value'
    bid_list:
      type: array
      description: A list of bids.
      items:
        $ref: '#/components/schemas/bid'  
  parameters:
    # Art Object
    path_artwork_id:
      name: artwork_id
      in: path
      required: true
      schema: 
        $ref: '#/components/schemas/id'
    # Auction
    path_auction_id:
      name: auction_id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/id'
    # Auction Item
    path_auction_item_id:
      name: auction_item_id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/id'
  responses:
    # Art Object
    get_artworks_200:
      description: Successfuly returned a list of Artworks.
      content: 
        application/json:
          schema:
            $ref: '#/components/schemas/artwork_list'
    get_artwork_200:
      description: Successfuly returned information about an art object.
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/artwork'
    # Auction
    get_auctions_200:
      description: Successfuly returned a list of auctions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/auction_list'
    get_auction_200:
      description: Successfuly returned information about an auction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/auction'
    # Auction Items
    get_auction_items_200:
      description: Successfuly returned a list of auction items given an auction id.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/auction_item_list'
    get_auction_item_200:
      description: Successfuly return an auction item given an auction and its id.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/auction_item'
    # Bids
    get_bids_200:
      description: Successfuly returned a list of bids
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/bid_list'