"""adding is active to user table

Revision ID: 002099120c11
Revises: 
Create Date: 2024-12-19 12:32:17.022866

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '002099120c11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
